---
sidebar: sidebar 
permalink: learn-well-architected-dashboard.html 
keywords: well-architected, best practices, well-architected system, best practices, well-architected framework, well-architected configurations, system management, system optimization, system configuration, system analysis 
summary: NetApp Console 中的架构完善仪表板可扫描系统配置，以评估可靠性、安全性、卓越运营、成本优化和性能效率，并提供见解和建议，帮助您实现卓越运营。 
---
= 了解 NetApp Console 中的架构完善仪表板
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory 可帮助您维护和操作可靠、安全、高效且经济高效的配置，这些配置与您使用的存储类型的良好架构框架保持一致。NetApp Console 中的良好架构仪表板提供了跨账户和区域的统一视图，可帮助团队识别风险并确定其优先级，并支持针对特定要求的自定义规则。对存储系统配置的每日自动扫描可提供见解和建议，以帮助您优化存储环境。



[[how-it-works]]
== 工作原理

Workload Factory 每天分析您的配置。该分析提供架构完善的状态、见解和建议，帮助您优化存储环境。

日常分析完成后，配置在架构良好的仪表板中显示为"优化"或"未优化"。您可以按架构良好的框架类别（可靠性、安全性、卓越运营、成本优化和性能效率）找到配置问题，并列出配置问题和建议。Workload Factory 可以自动修复某些问题，而其他问题则需要手动干预。在此情况下，建议会提供详细说明，以帮助您实施更改。

您可以忽略不适用于您环境的配置分析。忽略配置可避免不必要的警报和不准确的优化结果。



[[why-it-matters]]
== 为什么很重要

NetApp Workload Factory 通过将持续评估与建议见解和补救措施相结合，将最佳实践应用于大型存储、数据库和 VMware 环境。自动补救可减少人为错误，确保统一管理，并保持整个系统基础架构的性能和可靠性。



[[supported-storage-systems]]
== 支持的存储系统

Console 中架构完善的信息板支持以下存储系统：

* Amazon FSx for NetApp ONTAP
* Microsoft Azure 中的 Cloud Volumes ONTAP




[[get-started-with-netapp-console-to-detect-and-fix-system-misconfigurations]]
== 开始使用 NetApp Console 来检测和修复系统错误配置

要开始使用 NetApp Console，请注册、添加凭据并建立连接以管理资源并优化系统配置。

link:http://docs.netapp.com/us-en/console-setup-admin/task-quick-start-standard-mode.html["NetApp Console (SaaS 应用程序) 入门工作流"^]



[[related-information]]
== 相关信息

* link:fsx/improve-configurations-fsx.html["为 ONTAP 文件系统实施架构良好的 FSx"^]
* link:cvo/improve-configurations-cvo.html["实施架构良好的 Cloud Volumes ONTAP 系统"^]

