---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, well-architected, well-architected dashboard, amazon fsx for netapp ontap, fsx for ontap, cloud volumes ontap, microsoft azure' 
summary: 了解 NetApp Console 中精心设计的控制面板的新功能。 
---
= NetApp Console 中精心设计的控制面板的新增功能
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
了解 NetApp Console 中精心设计的控制面板的新功能。



[[17-august-2026]]
== 2026年8月17日



[[google-cloud-netapp-volumes-support-in-the-well-architected-dashboard]]
=== 在精心设计的控制面板中支持 Google Cloud NetApp Volumes

NetApp Console 控制面板现在支持 Google Cloud NetApp Volumes。存储管理员可以查看其存储池和配置的状态，获取提高效率、成本、性能、可靠性和安全性的建议，并采取行动优化操作并遵循最佳实践。

详细了解link:https://docs.netapp.com/us-en/console-well-architected/gcnv/configuration-analysis-gcnv.html["Google Cloud NetApp Volumes 的配置分析"]。



[[03-august-2026]]
== 2026年8月3日



[[fix-dismiss-and-reactivate-configurations-for-cloud-volumes-ontap-in-microsoft-azure]]
=== 修复、关闭和重新激活 Microsoft Azure 中 Cloud Volumes ONTAP 的配置

NetApp Console 中精心设计的仪表板现在允许您修复 Cloud Volumes ONTAP 系统的配置建议。

您还可以从良好架构分析中忽略一个或多个配置。这样，您可以忽略不适用于您的环境的特定配置。

如果稍后要包含已取消的配置，可以在架构良好的控制面板中重新激活该配置。这会将配置还原到分析中，并允许您获取其建议和修复。

link:https://docs.netapp.com/us-en/console-well-architected/cvo/\improve-configurations-cvo.html["修复、关闭和重新激活 Microsoft Azure 中 Cloud Volumes ONTAP 的配置"]



[[20-july-2026]]
== 2026年7月20日



[[introducing-the-well-architected-dashboard-in-netapp-console]]
=== 隆重推出 NetApp Console 中精心设计的控制面板

NetApp Console 中的精心设计的控制面板提供了跨帐户和区域的存储系统和配置的单一视图。控制面板提供见解和建议，以帮助您实现卓越运营。您可以查看配置的良好架构状态、由您使用的存储类型的良好架构框架的支柱组织的配置问题以及配置问题和建议列表。

详细了解 link:https://docs.netapp.com/us-en/console-well-architected/learn-well-architected-dashboard.html["精心设计的仪表板"]。

Console 中经过精心设计的仪表板可用于 link:https://docs.netapp.com/us-en/console-well-architected/cvo/configuration-analysis-cvo.html["Microsoft Azure 中的 Cloud Volumes ONTAP。"]



[[build-your-own-custom-rules]]
=== 创建自己的自定义规则

以通俗易懂的语言编写自定义规则，以确保您的系统遵循组织的标准和 NetApp 最佳实践。通过试运行测试规则，然后安排它们在您的环境中运行。

https://docs.netapp.com/us-en/console-well-architected/learn-custom-rules.html["详细了解自定义规则"]
