---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, well-architected, well-architected dashboard, amazon fsx for netapp ontap, fsx for ontap, cloud volumes ontap, microsoft azure' 
summary: 了解 NetApp Console 中精心设计的控制面板的新功能。 
---
= NetApp Console 中精心设计的控制面板的新增功能
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
了解 NetApp Console 中精心设计的控制面板的新功能。



[[17-august-2026]]
== 2026年8月17日



[[fsx-for-ontap-support-in-the-well-architected-dashboard-in-netapp-console]]
=== FSx for ONTAP 支持（在 NetApp Console 的架构完善仪表板中）

NetApp Console 中的架构完善控制面板适用于 Amazon FSx for NetApp ONTAP。

* link:https://docs.netapp.com/us-en/console-well-architected/fsx/configuration-analysis-fsx.html["了解 FSx for ONTAP 的配置分析"]




[[updated-configuration-names-for-fsx-for-ontap-in-the-well-architected-dashboard]]
=== 在架构良好的仪表板中更新了 FSx for ONTAP 的配置名称

NetApp Console 中的架构完善仪表盘现在包含 FSx for ONTAP 的新存储配置名称。

下表列出了架构良好的仪表板中的旧配置名称及其对应的新配置名称。

[cols="1,1"]
|===
| 旧配置名称 | 新配置名称 


| 计划卷备份 | 卷备份 


| SSD 容量阈值 | 固态硬盘容量余量 


| 文件容量阈值 | 文件容量净空 


| 长期保留数据的可靠性 | 复制策略标签 


| 计划的本地快照 | Snapshot 策略 


| 删除不必要的备份 | 备份过期时间 


| 删除不必要的快照 | Snapshot 到期 


| 未充分利用的固态硬盘容量 | SSD 容量过度配置 


| 非活动块设备 | 非活动数据块设备(LUN) 


| 通过冷数据分层优化总拥有成本 | 冷数据分层 


| 卷逻辑容量报告 | 主机可见容量报告 


| FlexGroup 卷重新平衡 | 重新平衡 FlexGroup 卷 


| FlexVol 卷重新平衡 | 重新平衡 FlexVol 卷 


| 缓存关系写入模式 | FlexCache 写入模式 


| 优化缓存卷大小 | FlexCache 副本大小 


| 未经授权访问卷 | 未经授权的 iSCSI 卷访问 


| ARP/AI 已禁用 | 勒索软件保护（ARP/AI） 
|===


[[well-architected-issues-displayed-in-netapp-console-systems-page]]
=== 在 NetApp Console 系统页面中显示的架构良好问题

Microsoft Azure 中 Cloud Volumes ONTAP 的架构良好问题通知可从 NetApp Console 的"存储管理系统"页面获取。此功能可帮助您快速识别 Azure 中 Cloud Volumes ONTAP 系统中的配置问题，并从通知导航到 Workloads 架构良好仪表板。



[[10-august-2026]]
== 2026年8月10日



[[google-cloud-netapp-volumes-support-in-the-well-architected-dashboard]]
=== 在精心设计的控制面板中支持 Google Cloud NetApp Volumes

NetApp Console 控制面板现在支持 Google Cloud NetApp Volumes。存储管理员可以查看其存储池和配置的状态，获取提高效率、成本、性能、可靠性和安全性的建议，并采取行动优化操作并遵循最佳实践。

详细了解link:https://docs.netapp.com/us-en/console-well-architected/gcnv/configuration-analysis-gcnv.html["Google Cloud NetApp Volumes 的配置分析"]。



[[03-august-2026]]
== 2026年8月3日



[[fix-dismiss-and-reactivate-configurations-for-cloud-volumes-ontap-in-microsoft-azure]]
=== 修复、关闭和重新激活 Microsoft Azure 中 Cloud Volumes ONTAP 的配置

NetApp Console 中精心设计的仪表板现在允许您修复 Cloud Volumes ONTAP 系统的配置建议。

您还可以从良好架构分析中忽略一个或多个配置。这样，您可以忽略不适用于您的环境的特定配置。

如果稍后要包含已取消的配置，可以在架构良好的控制面板中重新激活该配置。这会将配置还原到分析中，并允许您获取其建议和修复。

link:https://docs.netapp.com/us-en/console-well-architected/cvo/\improve-configurations-cvo.html["修复、关闭和重新激活 Microsoft Azure 中 Cloud Volumes ONTAP 的配置"]



[[20-july-2026]]
== 2026年7月20日



[[introducing-the-well-architected-dashboard-in-netapp-console]]
=== 隆重推出 NetApp Console 中精心设计的控制面板

NetApp Console 中的精心设计的控制面板提供了跨帐户和区域的存储系统和配置的单一视图。控制面板提供见解和建议，以帮助您实现卓越运营。您可以查看配置的良好架构状态、由您使用的存储类型的良好架构框架的支柱组织的配置问题以及配置问题和建议列表。

详细了解 link:https://docs.netapp.com/us-en/console-well-architected/learn-well-architected-dashboard.html["精心设计的仪表板"]。

Console 中经过精心设计的仪表板可用于 link:https://docs.netapp.com/us-en/console-well-architected/cvo/configuration-analysis-cvo.html["Microsoft Azure 中的 Cloud Volumes ONTAP。"]



[[build-your-own-custom-rules]]
=== 创建自己的自定义规则

以通俗易懂的语言编写自定义规则，以确保您的系统遵循组织的标准和 NetApp 最佳实践。通过试运行测试规则，然后安排它们在您的环境中运行。

https://docs.netapp.com/us-en/console-well-architected/learn-custom-rules.html["详细了解自定义规则"]
